[package]
name = "crabviz"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.7"
vial = "0.1"
clap = "4.0"
confy = " 0.5"
lazy_static = "1.4"

lsp-types = "0.93"

rayon = "1.5"
crossbeam-channel = "0.5"

serde = "1.0"
serde_json = "1.0"
shellexpand = "2.1"

walkdir = "2.3"
dashmap = "5.4"
