[package]
name = "crabviz"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# vial = "0.1"
vial = { git = "https://github.com/xvxx/vial" }
clap = "4.0"
confy = " 0.5"
lazy_static = "1.4"
snafu = { version = "0.7", features = ["backtraces-impl-std"]}

lsp-types = "0.93"

rayon = "1.5"
crossbeam-channel = "0.5"

serde = "1.0"
serde_json = "1.0"
shellexpand = "3.0"

walkdir = "2.3"
dashmap = "5.4"

[build-dependencies]
# vial = "0.1"
vial = { git = "https://github.com/xvxx/vial" }